parameters:
- name: TFVARS
  displayName: Terraform tfvars file
  type: string
  default: myvalues.tfvars
  values:
    - myvalues.tfvars
    - dev.tfvars
    - pt.tfvars
    - prod.tfvars
    
- name: TFACTION
  displayName: Terraform action to perform
  type: string
  default: apply
  values:
    - plan  
    - apply
    - destroy

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Pay-As-You-Go(69fc0447-bb32-4449-bce8-002d5b9938c9)'
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    environmentServiceName: 'Pay-As-You-Go(69fc0447-bb32-4449-bce8-002d5b9938c9)'
    commandOptions: '-var-file ${{ parameters.TFVARS }}'
    allowTelemetryCollection: true
  condition: eq(${{ parameters.TFACTION }}, "destroy")

