parameters:
  - name: VARSFILE
    displayName: VARSFILE
    default: myvalues.tfvars
    type: string 
    values:
      - myvalues.tfvars
      - dev.tfvars
      - pt.tfvars
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'Pay-As-You-Go(69fc0447-bb32-4449-bce8-002d5b9938c9)'
    commandOptions: '-var-file $(VARSFILE)'
    allowTelemetryCollection: true
